// example/src-test/src/App.vue
<template>
   <h1 class="green">Hello Vue</h1>
   <button @click="increment">{{ test }}</button>
</template>

<script setup>
import { ref } from "vue";
let test = ref(1);

function increment() {
   test.value += 1;
}

console.log("Hello vue");
</script>

<style lang="scss" scoped>
.green {
   color: rgb(95, 199, 124) !important;
}
</style>

// example/test-files/react/App.jsx
import React, { useState, useEffect } from "react";

export function App(props) {
   const [counter, setCount] = useState(1);
   useEffect(() => {
      console.log("Hello react");
   }, []);
   return (
      <div className="App">
         <h1>Hello React.</h1>
         <button onClick={() => setCount(counter + 1)}>{counter}</button>
      </div>
   );
}
